In [1]:
import numpy as np
np.__version__

'1.19.5'

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# 1 理解Python数据类型

## 1.1 Python整形不仅仅是一个数值

python3.4中的一个整形实际包括4个部分：
- ob_refcnt是一个引用计数
- ob_type是变量类型编码
- ob_size 指定数据大小（长度）
- ob_digit 包含实际整形值

> 每一个Python对象都是一个C语言结构体

## 1.2 Python列表不仅仅是一个列表
Python列表可以存储可变多元素，为了获得这些灵活的类型，列表中的每一项都是一个完整的python对象，这样不利于存储和操作数据。Numpy式数组与之相反。![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/array_vs_list.png)


## 1.3 python也可以创建紧凑数组
但是Numpy在紧凑存储的基础上提供了高效操作

In [3]:
import array
L=list(range(10))
A=array.array('i',L)
L
A

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
import sys
print("python数组的内存大小：%d" %sys.getsizeof(L))
print("紧凑型python数组的内存大小: %d" %sys.getsizeof(A))

python数组的内存大小：208
紧凑型python数组的内存大小: 104


In [5]:
X=np.array(L)
print("numpy数组大小： %d" %sys.getsizeof(X))
F=np.array(L,dtype="float")
print("设定数据类型为float的numpy数组大小： %d" %sys.getsizeof(X))

numpy数组大小： 176
设定数据类型为float的numpy数组大小： 176


In [6]:
#从python列表创建的嵌套列表构成的Numpy多维数组
i=1
np.array([range(i,i+3) for i in [1,2,3]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

## 1.4 从头创建数组

In [7]:
# 创建一个长度为10的数组，数组的值都是0
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# 创建一个3*5的浮点型数组，数组的值都是1
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# 创建一个3*5的浮点型数组，数组的值都是3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# 数组的值是线性序列，从0开始到20，步长2
np.arange(0,22,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
# 创建一个5个元素的数组，数组的值从0到1均匀分配
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# 创建一个3*3的,在0-1均匀分布的随机数组
np.random.random((3,3))
np.random.rand(3,3)

array([[0.22678307, 0.07354598, 0.13178721],
       [0.34642344, 0.81997784, 0.41140439],
       [0.26046435, 0.73271748, 0.4786785 ]])

array([[0.16478036, 0.86768194, 0.43555796],
       [0.07830969, 0.10830915, 0.97461334],
       [0.57862603, 0.18029926, 0.22227397]])

In [13]:
# 创建一个3*3的,均值为0，方差为1的正态分布的随机数组
np.random.normal(0,1,(3,3))

array([[ 0.13337283, -1.1114381 ,  1.66928751],
       [ 1.75406347,  0.90678134,  0.73744233],
       [-0.40455331,  1.04638205,  0.54134196]])

In [14]:
# 创建一个3*3的[0,10）区间的随机整数类型
np.random.randint(0,10,(3,3))

array([[5, 0, 2],
       [7, 0, 3],
       [4, 6, 8]])

In [15]:
# 创建一个3*3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# 创建一个由3个整数组成的未初始化的数组
np.empty(3)

array([1., 1., 1.])


Data type　　Description  
---  
bool_　　Boolean (True or False) stored as a byte  
int_　　　Default integer type (same as C long; normally either int64 or int32)  
intc　　Identical to C int (normally int32 or int64)  
intp　　Integer used for indexing (same as C ssize_t; normally either int32 or int64)  
int8	　　Byte (-128 to 127)  
int16	　　Integer (-32768 to 32767)  
int32	　　Integer (-2147483648 to 2147483647)  
int64	　　Integer (-9223372036854775808 to 9223372036854775807)  
uint8	　　Unsigned integer (0 to 255)  
uint16　　	Unsigned integer (0 to 65535)  
uint32　　	Unsigned integer (0 to 4294967295)  
uint64　　	Unsigned integer (0 to 18446744073709551615)  
float_	　　Shorthand for float64.  
float16	　　Half precision float: sign bit, 5 bits exponent, 10 bits mantissa  
float32	　　Single precision float: sign bit, 8 bits exponent, 23 bits mantissa  
float64	　　Double precision float: sign bit, 11 bits exponent, 52 bits mantissa  
complex_　	Shorthand for complex128.  
complex64　	Complex number, represented by two 32-bit floats  
complex128　　Complex number, represented by two 64-bit floats  

## Numpy数组基础

### Numpy数组的属性

In [17]:
np.random.seed(0)

x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))

In [18]:
#数组的维度、每个维度的大小、数组的元素数量、数组元素的数据类型、
print("x3的维度：",x3.ndim)
print("x3每个维度的大小:",x3.shape)
print("x3数组的大小:",x3.size)
print("X3元素的数据类型：",x3.dtype)
print("X3元素的字节大小：",x3.itemsize)
print("x3 数组总字节大小：",x3.nbytes)

x3的维度： 3
x3每个维度的大小: (3, 4, 5)
x3数组的大小: 60
X3元素的数据类型： int64
X3元素的字节大小： 8
x3 数组总字节大小： 480


In [19]:
x2.size

12

### 数组索引：获取单个元素

In [22]:
x1
x1[-1]
x1[0]

array([5, 0, 3, 3, 7, 9])

9

5

In [23]:
x2
x2[0,0]

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

3

### 数组切片


In [28]:
x=np.arange(10)
x
x[:5]
x[5:]
x[4:5]
x[::2]
x[::-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4])

array([5, 6, 7, 8, 9])

array([4])

array([0, 2, 4, 6, 8])

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
x2
x2[:2,]
x2[:2,:3]

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

array([[3, 5, 2, 4],
       [7, 6, 8, 8]])

array([[3, 5, 2],
       [7, 6, 8]])

In [33]:
x2[0]

array([3, 5, 2, 4])

In [39]:
#numpy返回的是数组的视图而不是副本
x2_sub_1=x2
x2_sub_1[0]=[4,3,2,1]
x2

array([[4, 3, 2, 1],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [38]:
#如果要创建副本
x2_sub_2=x2.copy()
x2_sub_2[0]=[4,3,2,1]
x2

array([[1, 2, 3, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

### 数组变形
reshape
newaxis

In [43]:
x2
x2.shape
x2.reshape((4,3))#
x2

array([[4, 3, 2, 1],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

(3, 4)

array([[4, 3, 2],
       [1, 7, 6],
       [8, 8, 1],
       [6, 7, 7]])

array([[4, 3, 2, 1],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [51]:
x=np.array([1,2,3])
x
x.reshape((1,3))
x[np.newaxis,:]

array([1, 2, 3])

array([[1, 2, 3]])

array([[1, 2, 3]])

### 数组拼接和分裂
拼接：concatenate vstack hstack
分裂：split hsplit vsplit 