In [6]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

import warnings
warnings.filterwarnings("ignore")

In [7]:
import numpy as np

import pandas as pd

pd.__version__

'1.2.1'

# Pandas对象简介


## pandas的Series对象
Pandas的Series对象是一个**带索引**数据构成的一维数组
Numpy数组通过隐式定义的整数索引获取数组，Pandas的Series对象用一种显式定义的索引与数值关联

### Series是通用的Numpy数组

In [ ]:
data=pd.Series([0.25,0.5,0.75,1.0])
data
data.values
data.index

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

array([0.25, 0.5 , 0.75, 1.  ])

RangeIndex(start=0, stop=4, step=1)

### Series是特殊的字典

In [ ]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

### 创建Series对象

In [ ]:
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [ ]:
pd.Series(5,index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [ ]:
pd.Series({2:'a',1:'b',3:'c'})

2    a
1    b
3    c
dtype: object

In [ ]:
pd.Series({2:'a',1:'b',3:'c'},index=[3,2])#Series对象只会保留显式定义的键值对

## Pandas的DataFrame对象

### DataFrame是通用的Numpy

In [ ]:

area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area
states=pd.DataFrame({'population':population,'area':area})
states
states.index
states.columns

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

Index(['population', 'area'], dtype='object')

### DataFrame是特殊的字典
在numpy二维数组中data[0]返回第一行，dataframe\[col0\]返回第一列

In [ ]:
states['population']
states.loc['Texas']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

population    26448193
area            695662
Name: Texas, dtype: int64

### 创建DataFrame对象

In [ ]:
#通过单个DataFrame对象创建
pd.DataFrame(population,columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [ ]:
#通过字典列表创建,缺失的值会用Nan(not a number)来表示
data=[{'a':i,'b':2*i} for i in range(3)]
pd.DataFrame(data)
pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

a  b
0  0  0
1  1  2
2  2  4

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [ ]:
#通过Series对象字典创建
pd.DataFrame({'population':population,'area':area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [ ]:
#通过numpy二维数组创建
pd.DataFrame(np.random.rand(3,2),columns=['foo','bar'],index=['a','b','c'])

foo       bar
a  0.920428  0.397977
b  0.363318  0.030885
c  0.111770  0.589904

In [ ]:
#通过numpy结构化数组创建
A=np.zeros(3,dtype=[('A','i8'),('B','f8')])
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## Pandas的Index对象
可以将Index对象看作一个**不可变数组或有序集合**
- 当看作不可变数组时，可以进行切片操作
- 当看作有序集合时，可以进行集合操作如join

In [ ]:
ind=pd.Index([2,3,5,7,11])
#当作不可变数组
ind[1]
ind[::2]
ind.size
ind.shape
ind.ndim
ind.dtype

3

Int64Index([2, 5, 11], dtype='int64')

5

(5,)

1

dtype('int64')

In [ ]:
#看作有序集合
indA=pd.Index([1,3,5,7,9])
indB=pd.Index([2,3,5,7,11])
indA & indB
indA | indB
indA ^ indB

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  after removing the cwd from sys.path.


Int64Index([3, 5, 7], dtype='int64')

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

Int64Index([1, 2, 9, 11], dtype='int64')

# 数据取值与选择

## Series数据选择方法

### 将Series看作字典

In [ ]:
data=pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
data
data['b']
'a' in data
data.keys()
list(data.items())
data['e']=1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

0.5

True

Index(['a', 'b', 'c', 'd'], dtype='object')

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### 将Series看作一维数组
当使用显示索引作切片时，结果包含最后一个索引，使用隐式索引作切片时，结果**不包含**最后一个索引

In [ ]:
#显式索引作为切片
data['a':'c']
#隐式索引作为切片
data[0:2]
#掩码
data[(data>0.3)&(data<0.8)]
#花哨的索引
data[['a','c']]

a    0.25
b    0.50
c    0.75
dtype: float64

a    0.25
b    0.50
dtype: float64

b    0.50
c    0.75
dtype: float64

a    0.25
c    0.75
dtype: float64

### 索引器：loc、iloc和ix

In [ ]:
data=pd.Series(['a','b','c'],index=[1,3,5])
data
#取值操作是显式索引
data[1]
#切片操作是隐式索引
data[1:3]


1    a
3    b
5    c
dtype: object

'a'

3    b
5    c
dtype: object

In [ ]:
#索引器不是Series对象的函数方法，而是暴露切片接口的属性
#loc属性，切片和取值都是显式的
data.loc[1]
data.loc[1:3]

'a'

1    a
3    b
dtype: object

In [ ]:
#第二种是iloc属性，取值和切片都是隐式

data.iloc[1]
data.iloc[1:3]
#第三种ix是前两种的混合形式，主要用于DataFrame对象

'b'

3    b
5    c
dtype: object

## DataFrame数据选择方法

### 将DataFrame看作字典

In [ ]:

area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [ ]:
data['area']
data.area#避免对用属性形式选取的列直接复制

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
data['density']=data['pop']/data['area']

### 将DataFrame看作二维数组 

In [ ]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [ ]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [ ]:
data.values[0]#使用单个行索引获取一行数据
data['area']#使用列索引获取一列数据

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [ ]:
data.iloc[:3,:2]#隐式
data.loc[:'Illinois',:'pop']#显式
#ix方法从1.0.0版开始移除

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

AttributeError: 'DataFrame' object has no attribute 'ix'

### 其他取值方法

In [ ]:
#对单个标签取值就选择列，对多个标签切片就选择阿航
data[1:3]#行数
data['Florida':'Illinois']#索引
data[data.density>100]#掩码

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

# Pandas数值运算
- 对于一元运算，输出结果保留索引和列标签
- 对于二元运算，pandas在传递通用函数时会自动对齐索引

## 通用函数：保留索引

In [ ]:
rng=np.random.RandomState(42)
ser=pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [ ]:
df=pd.DataFrame(rng.randint(0,10,(3,4)),columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [ ]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [ ]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

## 通用函数：对齐索引

### Series索引对齐

In [ ]:

area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [ ]:
area.index|population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [ ]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B
A.add(B,fill_value=0)

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### DataFrame索引对齐

In [ ]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [ ]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [ ]:
A+B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [ ]:
fill=A.stack().mean()
A.add(B,fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5


Python运算符与Pandas方法映射关系

|python运算符| pandas方法|
|---|---|
|+|	add()|
|-|	sub(), subtract()|
|*|	mul(), multiply()|
|/|	truediv(), div(), divide()|
|//|	floordiv()|
|%|	mod()|
|**|	pow()|

## 通用函数：DataFrame与Series的运算

In [ ]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [ ]:
A-A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [ ]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [ ]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

# 处理缺失值

## 选择处理缺失值的方法
- 用覆盖全局的掩码表示缺失值
- 用标签值表示缺失值

## Pandas的缺失值
pandas采用标签方法（nan或None）表示缺失值

### None:Python对象类型的缺失值
由于None是一个Python对象，所以不能作为任何Numpy/Pandas数组类型的缺失值，只能用于'object'数组类型，即由Python对象构成的数组

### Nan：数值类型的缺失值
Nan是一种按照IEEE浮点数标准设计、在任何系统中都兼容的特殊浮点数
无论和Nan进行何种操作，最终结果都是Nan

In [5]:
1+np.nan

nan

In [9]:
vals2=np.array([1,np.nan,3,4])
vals2.sum()
vals2.min()
vals2.max()

nan

nan

nan

In [10]:
np.nansum(vals2)
np.nanmin(vals2)
np.nanmax(vals2)

8.0

1.0

4.0

### Pandas中Nan与None的差异
Pandas会将没有标签值的数据类型自动转换为NA，也就是浮点型
Pandas会自动将None转换为Nan

## 处理缺失值
- isnull()
- notnull()
- dropna()
- fillna()

### 发现缺失值
isnull()和notnull(),返回布尔类型的掩码数据

In [13]:
data=pd.Series([1,np.nan,'hello',None])
data.isnull()
data[data.notnull()]

0    False
1     True
2    False
3     True
dtype: bool

0        1
2    hello
dtype: object

### 剔除缺失值
dropna()和fillna()

In [14]:
data
data.dropna()


0        1
1      NaN
2    hello
3     None
dtype: object

0        1
2    hello
dtype: object

In [17]:
#dataframe中没法单独剔除一个值，要么剔除缺失值所在的行要么是列。
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df
df.dropna()
df.dropna(axis='columns')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

0    1  2
1  2.0  3.0  5

2
0  2
1  5
2  6

In [ ]:
#通过设置how或者thresh参数来设置剔除行或者列缺失值的数量阈值

In [20]:
df[3]=np.nan
df
df.dropna(axis='columns',how='all')#设置为how=any，就是只要有缺失值就剔除整行或整列

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6